# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DegreePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Major', models.CharField(max_length=30)),
                ('Type', models.CharField(max_length=6)),
                ('Credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DegreeSem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.DegreePlan')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SemClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('Term', models.CharField(choices=[('F', 'Fall'), ('S', 'Spring'), ('SS', 'Summer')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UniClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('term', models.CharField(choices=[('F', 'Fall Only'), ('S', 'Spring Only'), ('FS', 'Fall/Spring'), ('FSS', 'Fall/Spring/Summer')], default='FS', max_length=3)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='semclass',
            name='Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.UniClass'),
        ),
        migrations.AddField(
            model_name='semclass',
            name='Semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.Semester'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.UniClass'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='CoReq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Coreqs', to='default.UniClass'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='PreReq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prereqs', to='default.UniClass'),
        ),
        migrations.AddField(
            model_name='degreesem',
            name='Semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.Semester'),
        ),
    ]
