# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degreeplan',
            name='id',
        ),
        migrations.AlterField(
            model_name='degreeplan',
            name='Major',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='degreeplan',
            name='Type',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
