# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0003_auto_20160225_1524'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UniClass',
            new_name='ClassListing',
        ),
    ]
