# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0005_auto_20160228_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='CoReq',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='PreReq',
        ),
        migrations.RemoveField(
            model_name='classlisting',
            name='desc',
        ),
        migrations.AddField(
            model_name='classlisting',
            name='prereqs',
            field=models.TextField(default='NONE'),
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
    ]
