# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0006_auto_20160229_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlisting',
            name='satisfies',
            field=models.TextField(default='NONE'),
        ),
    ]
