# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('default', '0008_classlisting_coreqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreePlanTemplate',
            fields=[
                ('Major', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SemesterTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDegreePlan',
            fields=[
                ('Major', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Entry', models.CharField(choices=[('F', 'Fall'), ('S', 'Spring')], default='F"', max_length=1)),
                ('CreditsRemaining', models.IntegerField()),
                ('Semesters', models.TextField()),
                ('LinkedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Semester',
            new_name='UserSemester',
        ),
        migrations.RemoveField(
            model_name='degreeplan',
            name='Semester1',
        ),
        migrations.RemoveField(
            model_name='degreeplan',
            name='Semester2',
        ),
        migrations.RemoveField(
            model_name='degreeplan',
            name='Semester3',
        ),
        migrations.RemoveField(
            model_name='degreeplan',
            name='Semester4',
        ),
        migrations.RemoveField(
            model_name='degreeplan',
            name='Semester5',
        ),
        migrations.RemoveField(
            model_name='degreeplan',
            name='Semester6',
        ),
        migrations.RemoveField(
            model_name='degreeplan',
            name='Semester7',
        ),
        migrations.RemoveField(
            model_name='degreeplan',
            name='Semester8',
        ),
        migrations.DeleteModel(
            name='DegreePlan',
        ),
        migrations.AddField(
            model_name='degreeplantemplate',
            name='Semester1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sem1', to='default.SemesterTemplate'),
        ),
        migrations.AddField(
            model_name='degreeplantemplate',
            name='Semester2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sem2', to='default.SemesterTemplate'),
        ),
        migrations.AddField(
            model_name='degreeplantemplate',
            name='Semester3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sem3', to='default.SemesterTemplate'),
        ),
        migrations.AddField(
            model_name='degreeplantemplate',
            name='Semester4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sem4', to='default.SemesterTemplate'),
        ),
        migrations.AddField(
            model_name='degreeplantemplate',
            name='Semester5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sem5', to='default.SemesterTemplate'),
        ),
        migrations.AddField(
            model_name='degreeplantemplate',
            name='Semester6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sem6', to='default.SemesterTemplate'),
        ),
        migrations.AddField(
            model_name='degreeplantemplate',
            name='Semester7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sem7', to='default.SemesterTemplate'),
        ),
        migrations.AddField(
            model_name='degreeplantemplate',
            name='Semester8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sem8', to='default.SemesterTemplate'),
        ),
    ]
