# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0009_auto_20160404_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeplantemplate',
            name='Semester1',
            field=models.TextField(default='NONE'),
        ),
        migrations.AlterField(
            model_name='degreeplantemplate',
            name='Semester2',
            field=models.TextField(default='NONE'),
        ),
        migrations.AlterField(
            model_name='degreeplantemplate',
            name='Semester3',
            field=models.TextField(default='NONE'),
        ),
        migrations.AlterField(
            model_name='degreeplantemplate',
            name='Semester4',
            field=models.TextField(default='NONE'),
        ),
        migrations.AlterField(
            model_name='degreeplantemplate',
            name='Semester5',
            field=models.TextField(default='NONE'),
        ),
        migrations.AlterField(
            model_name='degreeplantemplate',
            name='Semester6',
            field=models.TextField(default='NONE'),
        ),
        migrations.AlterField(
            model_name='degreeplantemplate',
            name='Semester7',
            field=models.TextField(default='NONE'),
        ),
        migrations.AlterField(
            model_name='degreeplantemplate',
            name='Semester8',
            field=models.TextField(default='NONE'),
        ),
    ]
