# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0011_auto_20160405_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdegreeplan',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdegreeplan',
            name='Major',
            field=models.CharField(max_length=30),
        ),
    ]
