# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0012_auto_20160405_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersemester',
            name='Credits',
            field=models.IntegerField(default=0),
        ),
    ]
